spring:
  profiles:
    active: prod


  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



  datasource:
    url: jdbc:postgresql://database-url:5432/schema
    username: username
    password: password
